### ISSUE TITLE
Selecionando uma amostra para os casos de teste

### ISSUE THREAD

**Issue by Luisa-Coelho** [danielfireman/ifal-qd#31]
### **Definição:** Serão realizados os testes em _2 diários por ano_ (**em todos os anos disponíveis**) repetindo-se através de um **padrão**.

**- Padrão do  mês**
JANEIRO - FEVEREIRO ... NOVEMBRO - DEZEMBRO

**- Padrão do dia**
02, 14 e 28.

_Portanto:_
02/01/2022 - 1° caso de teste (1° do ano 2022)
14/02/2022 - 2° caso de teste (2° do ano 2022)
28/03/2021 - 3° caso de teste (1° do ano 2021)
02/04/2021 - 4° caso de teste (2° do ano 2021)
14/05/2020 - 5° caso de teste (1° do ano 2020)
28/06/2020 - 6° caso de teste (2° do ano 2020)
... até 54°, sendo que o último será do ano de 1995;

Se somente estiver disponível a partir de 2009: serão 28, **então**:
02/01/2022
14/02/2022
28/03/2021
02/04/2021
14/05/2020
28/06/2020
02/07/2019
14/08/2019
28/09/2018
02/10/2018
14/11/2017
28/12/2017
02/01/2016
14/02/2016
28/03/2015
02/04/2015
14/05/2014
28/06/2014
02/07/2013
14/08/2013
28/09/2012
02/10/2012
14/11/2011
28/12/2011
02/01/2010
14/02/2010
28/03/2009
02/04/2009

**Comment by danielfireman** [comment]
Finalizada!
