### ISSUE TITLE
Inserir documentação da 1° fase do projeto

### ISSUE THREAD

**Issue by Luisa-Coelho** [danielfireman/ifal-qd#58]
Com respeito ao blog post que seria realizado, eu achei que era necessário a elaboração do texto lúdico para ficar pronto para divulgar. No entanto, foi recomendado que fosse feita uma documentação dessa 1° etapa para ser armazenada no repositório e com base nela então a equipe da OK elaborará o blog post.

Sendo assim, [neste documento](https://docs.google.com/document/d/1Y2UffD8u3Zjp8xsq2JNXEs4ipvqzcJk08oVc8b-bnOE/edit?usp=sharing) está um rascunho de como pode ser feito esse relatório. Eu me baseei no próprio pôster e adicionei mais coisas para que a lógica e os insights ficassem claros. Acho que também seria interessante mencionar sobre o progresso do trabalho e dos estudantes.

Fiquem à vontade quanto à apresentação do relatório. Pode ser um arquivo pdf simples ou até mesmo um [Github pages](https://pages.github.com/) se quiserem deixar mais bonito.

**Comment by danielfireman** [comment]
Já está disponível em https://danielfireman.github.io/ifal-qd/
