### ISSUE TITLE
Coletar e extrair todos os diários do mês de janeiro de 2022

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/ifal-qd#98]
Como um primeiro teste robusto do nosso extrator, gostaria que coletássemos todos os diários do ano de 2022 e extraíssemos os respectivos textos. Somado a isso, devemos devemos extrair os diários municipais de cada um dos diários extraídos. O formato a ser usado deve ser o seguinte:

- `diarios/2022/{mês}`

Por exemplo, o diretório `diarios/2022/01` deve conter todos os arquivos referentes ao mês de janeiro de 2022. Supondo o dia 03 de janeiro, os arquivos devem ser o seguinte:

- Fonte, ex. `2022-01-03-fonte.zip`: um zip contendo os arquivos `diario-2022-01-03.pdf`, `diario-2022-01-03-extraido.pdf` e os diversos textos extraídos dos diários municipais, por exemplo, diario-`2022-01-03-arapiraca.txt`.
- Resultado `2022-01-03-res.json`: para cada arquivo fonte o script deve gerar um arquivo no formato JSON contendo as informações dos atos separados por município.

O diretório `diarios` deve conter os scripts e um README.md documentando todo o processo para facilitar a extensão disso para outros meses. A análise deve ser dividida em duas partes:

1) Criação dos arquivos-fonte: deve existir um script para automação do processo de download dos dários em PDF, extrai os textos, executa o script para separação os arquivos de texto e realiza a compatação zip
2) Análise dos atos normativos a partir das fontes e geração do arquivo res: esse script deve descompactar o arquivo fonte e executar a análise dos atos normativos, com posterior criação do arquivo res.

**Comment by emanuelucas04** [comment]
Sobre o resultado, o JSON seguirá o mesmo padrão com o path, desc, cabeçalho?

**Comment by danielfireman** [comment]
Não. O arquivo de resultado tem objetivo diferente do arquivo de  teste.

Deve conter o caminho para o arquivo fonte e as informações extraídas dos diários e atos normativos.
